'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 computer.gltf --types t 
Author: Brandon Westlake (https://sketchfab.com/dr.badass2142)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/retro-computer-setup-free-82eaf2047e0447a1bfea22482f1d1404
Title: Retro Computer Setup (FREE)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useThree } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    retro_computer_setup_retro_computer_setup_Mat_0: THREE.Mesh
  }
  materials: {
    retro_computer_setup_Mat: THREE.MeshStandardMaterial
  }
  //animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Computer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Computer/computer.gltf') as GLTFResult

  const { viewport } = useThree();
  const positionX = -(viewport.width / 2); 
  const positionY = -(viewport.height / 2);
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.retro_computer_setup_retro_computer_setup_Mat_0.geometry} material={materials.retro_computer_setup_Mat} rotation={[-Math.PI / 2, 0, 0]} scale = {0.025} position ={[-positionX - 1.3, -2, 0]}/>
    </group>
  )
}

useGLTF.preload('/Computer/computer.gltf')
